server.port=8761

spring.application.name=eureka-server

#Eureka Specific Settings
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#Allow dashboard access
eureka.server.enable-self-preservation=false
